from feapder import Item, UpdateItem


class SpiderDataItem(Item):
    """
    This class was generated by feapder.
    command: feapder create -i spider_data.
    """

    def __init__(self, *args, **kwargs):
        # self.id = None
        self.title = None


class DemoDataItem(UpdateItem):
    """
    This class was generated by feapder.
    command: feapder create -i demo.
    """
    __update_key__ = ["url"]  # 更新title字段
    __unique_key__ = ["url"]  # 指定去重的key为 title、url，最后的指纹为title与url值联合计算的md5
    def __init__(self, *args, **kwargs):
        # self.id = None
        self.title = None
        self.url = None
        self.content = None
